#!/usr/bin/env node
// Serialize snarkjs (bn128) proof.json / verification_key.json / public.json
// into the exact byte layout expected by Soroban `crypto::bn254`
// (Ethereum / EIP-197 uncompressed, big-endian).
//
//   G1  : be32(x) || be32(y)                      (64 bytes)
//   G2  : Fp2(x) || Fp2(y),  Fp2(c) = be32(c1) || be32(c0)   (128 bytes)
//         ^^^ snarkjs stores Fp2 as [c0, c1] (real, imag); Soroban wants
//             c1 (imag) FIRST -> we SWAP the inner pair.
//   Fr  : be32(value)                             (32 bytes)
const fs = require('fs');
const path = require('path');
const dir = __dirname;

function be32(decStr) {
  const h = BigInt(decStr).toString(16);
  if (h.length > 64) throw new Error('field element overflow: ' + decStr);
  return h.padStart(64, '0');
}
const g1 = (p) => be32(p[0]) + be32(p[1]);                  // ignore z (=1, affine)
const fp2 = (c) => be32(c[1]) + be32(c[0]);                 // c1 || c0  (SWAP)
const g2 = (p) => fp2(p[0]) + fp2(p[1]);

const vk = JSON.parse(fs.readFileSync(path.join(dir, 'verification_key.json')));
const proof = JSON.parse(fs.readFileSync(path.join(dir, 'proof.json')));
const pub = JSON.parse(fs.readFileSync(path.join(dir, 'public.json')));

const out = {
  vk: {
    alpha: g1(vk.vk_alpha_1),
    beta: g2(vk.vk_beta_2),
    gamma: g2(vk.vk_gamma_2),
    delta: g2(vk.vk_delta_2),
    ic: vk.IC.map(g1),
  },
  proof: { a: g1(proof.pi_a), b: g2(proof.pi_b), c: g1(proof.pi_c) },
  pub_signals: pub.map(be32),
};

fs.writeFileSync(path.join(dir, 'serialized.json'), JSON.stringify(out, null, 2));

// Emit a Rust fixture (hex string consts) for the contract test.
const rustOut = process.argv[2];
if (rustOut) {
  const arr = (xs) => '&[' + xs.map((x) => `"${x}"`).join(', ') + ']';
  const rs = `// AUTO-GENERATED by spike/circuit/serialize.js — do not edit by hand.
// BN254 Groth16 fixture (a*b=c, a=3 b=11 c=33), hex (big-endian, EIP-197 layout).
#![allow(dead_code)]
pub const VK_ALPHA: &str = "${out.vk.alpha}";
pub const VK_BETA: &str = "${out.vk.beta}";
pub const VK_GAMMA: &str = "${out.vk.gamma}";
pub const VK_DELTA: &str = "${out.vk.delta}";
pub const VK_IC: &[&str] = ${arr(out.vk.ic)};
pub const PROOF_A: &str = "${out.proof.a}";
pub const PROOF_B: &str = "${out.proof.b}";
pub const PROOF_C: &str = "${out.proof.c}";
pub const PUB_SIGNALS: &[&str] = ${arr(out.pub_signals)};
`;
  fs.writeFileSync(rustOut, rs);
  console.log('wrote rust fixture:', rustOut);
}

// sanity: byte lengths
const len = (h) => h.length / 2;
console.log('alpha(G1) bytes:', len(out.vk.alpha));
console.log('beta(G2)  bytes:', len(out.vk.beta));
console.log('ic.len           :', out.vk.ic.length, '(== nPublic+1 =', vk.nPublic + 1, ')');
console.log('proof.a bytes    :', len(out.proof.a), '| proof.b bytes:', len(out.proof.b));
console.log('pub_signals      :', out.pub_signals);
console.log('wrote serialized.json');
